import './globals.css'
import type { Metadata } from 'next'
import { Anton } from 'next/font/google'

const anton = Anton({weight: '400', subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={anton.className}>{children}</body>
    </html>
  )
}
